version: "3.2"

services:
    grafana:
      image: grafana/grafana:latest
      container_name: sample_grafana
      ports: 
        - "8000:8000" # tcp
        - "3000:3000" # web
      volumes:
        - type: bind
          source: "${PWD}/lib/grafana"
          target: /var/lib/grafana
      networks:
        - monitor
      restart: always
      depends_on:
        - prometheus

    prometheus:
      image: prom/prometheus:v2.24.0
      container_name: sample_prometheus
      volumes:
        - type: bind
          source: "${PWD}/etc/prometheus"
          target: /etc/prometheus
          read_only: true
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      networks:
        - monitor
      restart: always

    node-exporter:
      image: prom/node-exporter:latest
      container_name: sample_node-exporter
      ports:
        - 9100:9100
      networks:
        - monitor
      restart: always
      depends_on:
        - prometheus

networks:
    monitor:
        driver: bridge
